# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class DB_LOADERStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.transfer_DB = channel.stream_unary(
                '/DB_LOADER/transfer_DB',
                request_serializer=server__pb2.Text.SerializeToString,
                response_deserializer=server__pb2.Text.FromString,
                )
        self.transfer_DES_key = channel.unary_unary(
                '/DB_LOADER/transfer_DES_key',
                request_serializer=server__pb2.Text.SerializeToString,
                response_deserializer=server__pb2.Text.FromString,
                )


class DB_LOADERServicer(object):
    """Missing associated documentation comment in .proto file."""

    def transfer_DB(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def transfer_DES_key(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DB_LOADERServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'transfer_DB': grpc.stream_unary_rpc_method_handler(
                    servicer.transfer_DB,
                    request_deserializer=server__pb2.Text.FromString,
                    response_serializer=server__pb2.Text.SerializeToString,
            ),
            'transfer_DES_key': grpc.unary_unary_rpc_method_handler(
                    servicer.transfer_DES_key,
                    request_deserializer=server__pb2.Text.FromString,
                    response_serializer=server__pb2.Text.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DB_LOADER', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DB_LOADER(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def transfer_DB(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/DB_LOADER/transfer_DB',
            server__pb2.Text.SerializeToString,
            server__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def transfer_DES_key(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DB_LOADER/transfer_DES_key',
            server__pb2.Text.SerializeToString,
            server__pb2.Text.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
